# -*- coding: utf-8 -*-
"""Project - Retail Business Performance & Profitability Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104yQ3_0RVoBzpa0Z9Zi0THhXdCpsH3TL

Using Python

1.Data Cleaning and Preprocessing
"""

import pandas as pd

df = pd.read_csv("/sample_retail_data.csv")
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Example: create Profit column
df['Profit'] = df['Sales'] - df['Cost']

"""2.Exploratory Data Analysis (EDA)

a. Sales, Cost, and Profit Over Time
"""

df.set_index('Order Date').resample('M')[['Sales', 'Cost', 'Profit']].sum().plot()

"""b. Category-wise Profitability"""

df.groupby('Category')['Profit'].sum().sort_values(ascending=False).plot(kind='bar')

"""c. Region-wise or Segment-wise Analysis"""

df.groupby('Region')['Profit'].sum().plot(kind='barh')

"""d. Top 10 Most Profitable Products"""

df.groupby('Product')['Profit'].sum().sort_values(ascending=False).head(10)

"""3.Correlation and Trend Insights

Correlation matrix for Sales, Cost, Profit, Quantity, etc.
"""

import seaborn as sns
sns.heatmap(df[['Sales', 'Cost', 'Profit', 'Quantity']].corr(), annot=True)

"""Profit trends over quarters/seasons:"""

df['Quarter'] = df['Order Date'].dt.to_period('Q')
df.groupby('Quarter')['Profit'].sum().plot()